#!/bin/bash

# Easy way of extending bootstrap, just run
# this script inside main bootstrap directory
# directory.

# It will create './less/custom' dir with less files connected with
# bootstrap base by adding proper import statement, eg:
# @import 'custom/variables.less' at the end of variable.less

#####

# go to proper directory
cd './less/';

CUSTOM_DIR='custom/'
LESS_FILES=`ls *.less`

# make custom dir
if [ ! -d "$CUSTOM_DIR" ] ; then
    mkdir "$CUSTOM_DIR"
    echo "Created $CUSTOM_DIR!"
fi

# rest of custom
for file in $LESS_FILES ; do
    is_extended=`cat "$file" | grep "${CUSTOM_DIR}${file}"`
    if [ -z "$is_extended" ] ; then
        printf "\n@import \"${CUSTOM_DIR}${file}\";\n" >> $file
        echo "Extended file '$file'..."
    fi

    if [ ! -e "${CUSTOM_DIR}$file" ] ; then
        printf "// extends ../$file  \n\n" > "${CUSTOM_DIR}$file"
        echo "Added file '${CUSTOM_DIR}$file'..."
    fi
done

cd '../';
