#!/bin/bash

# Easy way of extending bootstrap, just run
# this script inside main bootstrap directory
# directory.

# It will create './less/custom' dir with less files connected with
# bootrstrap base by adding proper import statement, eg:
# @import 'custom/variables.less' at the end of variable.less

#####

# go to proper direcotry
cd './less/';

CUSTOM_DIR='custom/'
LESS_FILES=`ls *.less`

# make custom dir
if [ ! -d "$CUSTOM_DIR" ] ; then
    mkdir "$CUSTOM_DIR"
    echo "Created $CUSTOM_DIR!"
fi

# make base.less
if [ ! -e "$CUSTOM_DIR/base.less" ] ; then
   printf "/*\n   HERE put your own CSS things,\n   we import all variables and mixins from,\n   so feel free to use them!\n*/" > "$CUSTOM_DIR/base.less"
   echo "Creaded custom/base.less!"
fi

# rest of custom
for file in $LESS_FILES ; do
    is_extended=`cat "$file" | grep "'${CUSTOM_DIR}${file}'"`
    if [ -z "$is_extended" ] ; then
        printf "\n@import '${CUSTOM_DIR}${file}'\n" >> $file
        echo "Extended file '$file'..."
    fi

    if [ ! -e "${CUSTOM_DIR}$file" ] ; then
        printf "/* extends ../$file  */\n\n" > "${CUSTOM_DIR}$file"
        echo "Added file '${CUSTOM_DIR}$file'..."
    fi
done

cd '../';
